### ISSUE TITLE
my problems

### ISSUE THREAD

**Issue by sunbingxin-jpg** [41monster/RePIT_NaturalCirculation2D#2]
I'm sorry to trouble you, but I have two questions. Firstly, I would like to use data from 5-5.05 to predict time periods that are not available in the dataset, such as 5.06. Secondly, the predicted file generated by the code is a 200 * 200 matrix, and the original real value is 1 * 500. How should I compare.

**Comment by shilaj** [comment]
Can you please, paste your error pictures in these issues box? Because, I couldn't view it. 
And there is **config.py** file where you can configure to your use case, please make changes in the config file and try it again.

**Comment by sunbingxin-jpg** [comment]
Sorry, I have added the pictures and data to the attachment. p,ux,uy are my variables.




Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月4日(星期三) 下午4:01
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Can you please, paste your error pictures in these issues box? Because, I couldn't view it.
 And there is config.py file where you can configuration your use, please make changes in the config file and try it again.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

traindata0.2.csv (18.28M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=733734359db1ec985faf5a08403405494e4355045e000f561b07500c551954005706190c5e06004b0354020003015552055106566624371244565d5b025543070619061b054741660b&code=6745f47f




traindata0.1.csv (18.29M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=236430652853bfcb0ffc5e584733561a1e105303550154564b540452541e065003561d520456011854060207590a060102500251612364411405590b05521054564a014b024012355b&code=fd0ea3d5




traindata0.csv (11.50M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=7136363729cf72c65bae580a1e3007164a4255540a54015b1f0454520b1d0c5c07501b52010553140600070e0a01045a0a055756383e354d40575f595c514158021855444e3008&code=26678059




centres(2).csv (8.16M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=756539636b571e9e5ffd575e4030514e4e115c53025301031b060d52541d5000575014020300544c500409015109015600575c01663e6302530b4d1103434b531f4b5a1010305e&code=6e9cf0ca

**Comment by sunbingxin-jpg** [comment]
I'm sorry, I have learned the real data. But can we generate a prediction result of 5.06 in the end, and then import it into Openfoam to continue the calculation.



发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Wed,Dec 4,2024 4:01 PM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Can you please, paste your error pictures in these issues box? Because, I couldn't view it.
 And there is config.py file where you can configuration your use, please make changes in the config file and try it again.

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg, sorry for the late reply. 
Yes, we can do it but I am afraid the functionalities in this repo are not capable of doing so. 
For now, you have to do the post-processing part yourself. Thank you.

**Comment by sunbingxin-jpg** [comment]
I'm sorry to hear this news, but I ran a 600 * 600 data using your previous hard coded code and encountered an indexing error.



发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Tue,Dec 10,2024 0:30 PM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Hi @sunbingxin-jpg, sorry for the late reply.
 Yes, we can do it but I am afraid the functionalities in this repo are not capable of doing so.
 For now, you have to do the post-processing part yourself. Thank you.

**Comment by shilaj** [comment]
@sunbingxin-jpg 
Have you tried running the latest code with the changes you want?
If you face any errors while running the code, please I request you to direct us on how you got into the error with the error message. This way we would be able to pin-point the problem and would be easier for us to solve it. 

In our previous comments, I noticed that you said you uploaded the screenshots of the errors but we were not being able to see your images. Maybe, before hitting the comment button, can you please ensure from your side that the images you are trying to share with us have been uploaded in the issue section properly? 

Thank you for your interest and patience.

**Comment by sunbingxin-jpg** [comment]
I am sorry, there are still problems with using my own data. The attachment is my data and the picture of the problem. If I set unavailable data in the config, the print result will still be run, and the error as shown in the dataset.py will appear.




Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月16日(星期一) 上午10:47
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
@sunbingxin-jpg
 Have you tried running the latest code with the changes you want?
 If you face any errors while running the code, please I request you to direct us on how you got into the error with the error message. This way we would be able to pin-point the problem and would be easier for us to solve it.
 
In our previous comments, I noticed that you said you uploaded the screenshots of the errors but we were not being able to see your images. Maybe, before hitting the comment button, can you please ensure from your side that the images you are trying to share with us have been uploaded in the issue section properly?
 
Thank you for your interest and patience.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

DATA.zip (79.23M, 2025年01月16日 11:48 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=04343737c12b3ccf50ac590a1562021b414004510b53510314515605574f51570d521a0e525153195c0502540a52080201040e07336a307078607619490b403404&code=94773b04

**Comment by sunbingxin-jpg** [comment]
F:\Anaconda3\envs\pytorch-gpu\python.exe F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py&nbsp;
Traceback (most recent call last):
&nbsp; File "F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py", line 270, in <module&gt;
&nbsp; &nbsp; data = FVMNDataset(training_config,data_path, start_time, end_time, time_step)
&nbsp; File "F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py", line 57, in __init__
&nbsp; &nbsp; self.inputs, self.labels = self._prepare_inputs_and_labels()
&nbsp; File "F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py", line 245, in _prepare_inputs_and_labels
&nbsp; &nbsp; inputs.append(self._prepare_input(time))
&nbsp; File "F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py", line 183, in _prepare_input
&nbsp; &nbsp; numpy_data = [self.parse_numpy(self.training_config, data_path) for data_path in full_data_path]
&nbsp; File "F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py", line 183, in <listcomp&gt;
&nbsp; &nbsp; numpy_data = [self.parse_numpy(self.training_config, data_path) for data_path in full_data_path]
&nbsp; File "F:\fvmn3\RePIT_NaturalCirculation2D-main\dataset.py", line 105, in parse_numpy
&nbsp; &nbsp; y_data = data[:,1].reshape(grid_y, grid_x, order="C")
IndexError: index 1 is out of bounds for axis 1 with size 1





The above is the error message prompted by dataset.py


Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月16日(星期一) 上午10:47
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
@sunbingxin-jpg
 Have you tried running the latest code with the changes you want?
 If you face any errors while running the code, please I request you to direct us on how you got into the error with the error message. This way we would be able to pin-point the problem and would be easier for us to solve it.
 
In our previous comments, I noticed that you said you uploaded the screenshots of the errors but we were not being able to see your images. Maybe, before hitting the comment button, can you please ensure from your side that the images you are trying to share with us have been uploaded in the issue section properly?
 
Thank you for your interest and patience.

**Comment by shilaj** [comment]
@sunbingxin-jpg,  
The error you are facing doesn't seem like the problem with the code, because in the line throwing the error it is saying that the index is out of  bounds, this means that in the **config.py** file the data_dim parameter is set to 2 but the dimension of the data you're trying to read from numpy file is not 2D; hence it threw this error. 

Can you please tell me, what is the dimension of the data you have? 
Because, to run this code on the dataset part: 
- We are dividing data into scalars and vectors; you can see in the config file as **data_vars**
- Based on these division, code will look for data in the assets directory (also defined in config file)
- If the variable is vector: the numpy data in the assets directory should be of shape [x, 1] if 1D; [x,2] if 2D; [x,3] if 3D. At the same time, you must specify the **data_dim** parameter in the config file based on the data you have. 
For example: 
For time_step: 10.02
data_vars: {"scalars":"T", "vectors":"U"}
data_dim = 2
Then there must be .npy file for T and U as T_10.02.npy and U_10.02.npy respectively in the assets directory where the shape of the T data should be (x,) and U data should be (x,2) or (x,3) **but can't be (x,1) if data_dim == 2.** --> I think this is the exactly why you're facing the error. 

I hope I am making sense to you. If you have further queries, feel free to ask. 
But I request you to closely analyse the functionalities and the parameters in the config file before carrying out any operation. 
Thank you.

**Comment by sunbingxin-jpg** [comment]
Thank you very much, I ran the code successfully, I want to solve ns equation problem, thanks again




Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月17日(星期二) 下午2:07
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
@sunbingxin-jpg,
 The error you are facing doesn't seem like the problem with the code, because in the line throwing the error it is saying that the index is out of  bounds, this means that in the config.py file the data_dim parameter is set to 2 but the dimension of the data you're trying to read from numpy file is not 2D; hence it threw this error.
 
Can you please tell me, what is the dimension of the data you have?
 Because, to run this code on the dataset part:
  
We are dividing data into scalars and vectors; you can see in the config file as data_vars
 
Based on these division, code will look for data in the assets directory (also defined in config file)
 
If the variable is vector: the numpy data in the assets directory should be of shape [x, 1] if 1D; [x,2] if 2D; [x,3] if 3D. At the same time, you must specify the data_dim parameter in the config file based on the data you have.
 For example:
 For time_step: 10.02
 data_vars: {"scalars":"T", "vectors":"U"}
 data_dim = 2
 Then there must be .npy file for T and U as T_10.02.npy and U_10.02.npy respectively in the assets directory where the shape of the T data should be (x,) and U data should be (x,2) or (x,3) but can't be (x,1) if data_dim == 2. --&gt; I think this is the exactly why you're facing the error.
  
I hope I am making sense to you. If you have further queries, feel free to ask.
 But I request you to closely analyse the functionalities and the parameters in the config file before carrying out any operation.
 Thank you.

**Comment by sunbingxin-jpg** [comment]
Sorry, when I compared the data you provided, I found a big gap in the internal data of T_10.04_predicted.npy and T_10.04.npy T_10.05_predicted.npy and T_10.05.npy.





Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月17日(星期二) 下午2:07
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
@sunbingxin-jpg,
 The error you are facing doesn't seem like the problem with the code, because in the line throwing the error it is saying that the index is out of  bounds, this means that in the config.py file the data_dim parameter is set to 2 but the dimension of the data you're trying to read from numpy file is not 2D; hence it threw this error.
 
Can you please tell me, what is the dimension of the data you have?
 Because, to run this code on the dataset part:
  
We are dividing data into scalars and vectors; you can see in the config file as data_vars
 
Based on these division, code will look for data in the assets directory (also defined in config file)
 
If the variable is vector: the numpy data in the assets directory should be of shape [x, 1] if 1D; [x,2] if 2D; [x,3] if 3D. At the same time, you must specify the data_dim parameter in the config file based on the data you have.
 For example:
 For time_step: 10.02
 data_vars: {"scalars":"T", "vectors":"U"}
 data_dim = 2
 Then there must be .npy file for T and U as T_10.02.npy and U_10.02.npy respectively in the assets directory where the shape of the T data should be (x,) and U data should be (x,2) or (x,3) but can't be (x,1) if data_dim == 2. --&gt; I think this is the exactly why you're facing the error.
  
I hope I am making sense to you. If you have further queries, feel free to ask.
 But I request you to closely analyse the functionalities and the parameters in the config file before carrying out any operation.
 Thank you.

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg, thank you for sharing your concern with us. We will look into it thoroughly, please update us if you find anything alarming regarding the prediction. Thank you!

**Comment by sunbingxin-jpg** [comment]
I'm sorry to hear that, &nbsp;I'm looking forward to this problem being solved.

发自我的iPhone


------------------ Original ------------------
From: Baral ***@***.***&gt;
Date: Mon,Dec 23,2024 9:24 AM
To: 41monster/RePIT_NaturalCirculation2D ***@***.***&gt;
Cc: sunbingxin-jpg ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Hi @sunbingxin-jpg, thank you for sharing your concern with us. We will look into it thoroughly, please update us if you find anything alarming regarding the prediction. Thank you!

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg. Sorry for taking up such a long time to fix the issue. But, can you please try it now. Everything should work as expected. If you face any problems, please feel free to ask us. 
Thank you!

**Comment by sunbingxin-jpg** [comment]
Thank you very much. I ran it and it matched up this time. There are still some small problems. 1. When I ran it, I found that it was not running on the gpu. 2. I want to view the training time and prediction time separately. How can I separate the code, such as the trained one? The model is saved as a py file to count the training time, and then the trained model is saved separately as another py file to run the prediction statistics time. 3 You said that the boundaries need to be filled with the latest data. I found that the boundaries of u-10.0-u10.05 are very similar. It can be approximated that they all fill the initial boundaries. During the calculation process, only the variables in the internal area are updated.




Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月8日(星期三) 下午2:15
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Hi @sunbingxin-jpg. Sorry for taking up such a long time to fix the issue. But, can you please try it now. Everything should work as expected. If you face any problems, please feel free to ask us.
 Thank you!

**Comment by shilaj** [comment]
Hi @sunbingxin-jpg. Thank you for your comments. To answer your questions:
1. It should run on gpu because I have tested it, maybe your cuda is not installed properly, can you please check that? 
The simple test you can do is `torch.cuda.is_available()` in any python script; if it returns true then the code will definitely run on gpu. 
2. That is quite not a problem related to the code, still I think there are train and predict methods in the Trainer class, so comment anything below the `trainer.train()` and you can start the prediction the way you want; to get the idea you can check on **predict()** method in Trainer class. 
3. Thank you so much for your suggestion but I think it seems same because the time interval is quite low; if you check the later timestamps, let's say 10.05 and 11.05 then there's a difference. 

Please, feel free to reach out to us, if you have any further queries.

**Comment by sunbingxin-jpg** [comment]
Thank you very much. I will modify it myself. There is no problem for the time being. Sorry for your trouble. Thank you again.




Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月9日(星期四) 下午4:31
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Hi @sunbingxin-jpg. Thank you for your comments. To answer your questions:
  
It should run on gpu because I have tested it, maybe your cuda is not installed properly, can you please check that?
 The simple test you can do is torch.cuda.is_available() in any python script; if it returns true then the code will definitely run on gpu.
 
That is quite not a problem related to the code, still I think there are train and predict methods in the Trainer class, so comment anything below the trainer.train() and you can start the prediction the way you want; to get the idea you can check on predict() method in Trainer class.
 
Thank you so much for your suggestion but I think it seems same because the time interval is quite low; if you check the later timestamps, let's say 10.05 and 11.05 then there's a difference.
  
Please, feel free to reach out to us, if you have any further queries.

**Comment by shilaj** [comment]
Thank you. Have a nice time!

**Comment by sunbingxin-jpg** [comment]
Sorry, there is another small question. If I want to predict data outside the data set, such as 10.06, then change 10.05 to 10.06 in config.py




Kevin&nbsp;Durant
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "41monster/RePIT_NaturalCirculation2D"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年1月9日(星期四) 下午4:38
***@***.***&gt;;
抄送:&nbsp;"Kevin ***@***.******@***.***&gt;;
主题:&nbsp;Re: [41monster/RePIT_NaturalCirculation2D] my problems (Issue #2)





 
Thank you. Have a nice time!
